/* Copyright (c) 2022 Toriti Tech Team https://t.me/ToritiTech */

module.exports = {
  STAFF_ERROR: {
    DUPLICATED_USER: 'DUPLICATED_USER',
    DUPLICATED_USER_EMAIL: 'DUPLICATED_USER_EMAIL',
    DUPLICATED_USER_PHONE: 'DUPLICATED_USER_PHONE',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    USER_LOCKED: 'USER_LOCKED',
    USERNAME_OR_PASSWORD_NOT_MATCH: 'USERNAME_OR_PASSWORD_NOT_MATCH',
  },
  STAFF_ACTIVE: '1',
};
