/* Copyright (c) 2022 Toriti Tech Team https://t.me/ToritiTech */

export const FETCH_APPS_REQUEST = 'FETCH_APPS_REQUEST';
export const FETCH_APPS_SUCCESS = 'FETCH_APPS_SUCCESS';
export const FETCH_APP_CHANGE = 'FETCH_APP_CHANGE';
export const FETCH_APP_CONFIGURATION_REQUEST = 'FETCH_APP_CONFIGURATION_REQUEST';
export const FETCH_APP_CONFIGURATION_SUCCESS = 'FETCH_APP_CONFIGURATION_SUCCESS';
