/* Copyright (c) 2022 Toriti Tech Team https://t.me/ToritiTech */

module.exports = {
  USER_VERIFY_INFO_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3,
  },
  USER_SEX: {
    MALE: 0,
    FEMALE: 1,
  },
  USER_TYPE: {
    PERSONAL: 1,
    REALESTATEBROKER: 2,
  },
  USER_VERIFY_EMAIL_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3,
  },
  USER_VERIFY_PHONE_NUMBER_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3,
  },
  USER_ERROR: {
    DUPLICATED_USER: 'DUPLICATED_USER',
    DUPLICATED_USER_EMAIL: 'DUPLICATED_USER_EMAIL',
    DUPLICATED_USER_PHONE: 'DUPLICATED_USER_PHONE',
    INVALID_REFER_USER: 'INVALID_REFER_USER',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    USER_LOCKED: 'USER_LOCKED',
    NOT_VERIFIED_EMAIL: 'NOT_VERIFIED_EMAIL',
    NOT_VERIFIED_PHONE: 'NOT_VERIFIED_PHONE',
    REFER_USER_NOT_FOUND: 'REFER_USER_NOT_FOUND',
    OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  },
  USER_MEMBER_LEVEL: {
    LV0: 'LV0',
    LV1: 'LV1',
    LV2: 'LV2',
    LV3: 'LV3',
    LV4: 'LV4',
    LV5: 'LV5',
    LV6: 'LV6',
    LV7: 'LV7',
    LV8: 'LV8',
    LV9: 'LV9',
    LV10: 'LV10',
  },
};
